# Generated by Django 5.2.12 on 2026-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speeches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('on_behalf_of', models.CharField(blank=True, max_length=300, null=True)),
                ('text', models.TextField()),
                ('position_in_document', models.IntegerField()),
                ('position_in_item', models.IntegerField()),
            ],
            options={
                'db_table': 'speeches',
                'ordering': ['position_in_document'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StageDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('direction_type', models.CharField(choices=[('adoption', 'Adoption'), ('decision', 'Decision'), ('suspension', 'Suspension'), ('resumption', 'Resumption'), ('adjournment', 'Adjournment'), ('silence', 'Silence'), ('language_note', 'Language Note'), ('other', 'Other')], max_length=20)),
                ('position_in_document', models.IntegerField()),
                ('position_in_item', models.IntegerField()),
            ],
            options={
                'db_table': 'stage_directions',
                'ordering': ['position_in_document'],
                'managed': False,
            },
        ),
    ]
