version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: redis
  mongodb:
    image: mongo:3.2.3
    ports:
      - "27017:27017"
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python web/manage.py makemigrations && python web/manage.py migrate && python web/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - mongodb
    environment:
        - VIRTUAL_HOST=un-project.org,en.un-project.org,fr.un-project.org
