from django.conf.urls import url
from declarations.views import HomeView, SearchView
from declarations.views import (ResolutionDetailView, HomeView,
                            ResolutionCreationView, DeclarationCreationView,
                            DeclarationDeleteView, ResolutionJsonView,
                            DeclarationEditView, ResolutionUpdateView,
                            ResolutionPublishView, ResolutionUnpublishView,
                            ResolutionDeleteView, AboutView, NewsView,
                            UpdatedResolutionsView, ReportView, RemoveReportView,
                            ControversialResolutionsView, TosView, SearchView,
                            NotificationsView, DeclarationSupportView, DeclarationUnsupportView,
                            StatsView, FallaciesView, FeaturedJSONView, NewsJSONView,
                            RandomResolutionView)


urlpatterns = [
   url(r'^$', HomeView.as_view(), name='home'),
   url(r'^notifications$', NotificationsView.as_view(), name='notifications'),
   url(r'^featured.json$', FeaturedJSONView.as_view(), name='resolutions_featured_json'),
   url(r'^news.json$', NewsJSONView.as_view(), name='resolutions_latest_json'),
   url(r'^news$', NewsView.as_view(),
       name='resolutions_latest'),
   url(r'^search$', SearchView.as_view(),
       name='resolutions_search'),
   url(r'^random$', RandomResolutionView.as_view(),
       name='resolutions_random'),
   url(r'^updated$', UpdatedResolutionsView.as_view(),
       name='resolutions_updated'),
   url(r'^controversial', ControversialResolutionsView.as_view(),
       name='resolutions_controversial'),
   url(r'^stats$', StatsView.as_view(),
       name='resolutions_stats'),
    url(r'^fallacies$', FallaciesView.as_view(),
       name='fallacies'),
   url(r'^about$',
       AboutView.as_view(),
       name='about'),
   url(r'^tos$',
       TosView.as_view(),
       name='tos'),
   url(r'^new-resolution$',
       ResolutionCreationView.as_view(),
       name='new_resolution'),
   url(r'^(?P<slug>[\w-]+)/edit$',
        ResolutionUpdateView.as_view(),
        name='resolution_edit'),
   url(r'^(?P<slug>[\w-]+)\.json$',
        ResolutionJsonView.as_view(),
        name='resolution_detail_json'),
   url(r'^(?P<slug>[\w-]+)$',
        ResolutionDetailView.as_view(),
        name='resolution_detail'),
   url(r'^(?P<slug>[\w-]+)/(?P<declaration_id>[\d+]+)$',
        ResolutionDetailView.as_view(),
        name='declaration_detail'),
   url(r'^(?P<slug>[\w-]+)/declarations/(?P<pk>[0-9]+)/unsupport',
        DeclarationUnsupportView.as_view(),
        name='unsupport_declaration'),
   url(r'^(?P<slug>[\w-]+)/declarations/(?P<pk>[0-9]+)/support',
        DeclarationSupportView.as_view(),
        name='support_declaration'),
   url(r'^(?P<slug>[\w-]+)/declarations/(?P<pk>[0-9]+)/delete',
        DeclarationDeleteView.as_view(),
        name='delete_declaration'),
   url(r'^(?P<slug>[\w-]+)/declarations/(?P<pk>[0-9]+)/report',
        ReportView.as_view(),
        name='report_declaration'),
   url(r'^(?P<slug>[\w-]+)/declarations/(?P<pk>[0-9]+)/unreport',
        RemoveReportView.as_view(),
        name='unreport_declaration'),
   url(r'^(?P<slug>[\w-]+)/declarations/(?P<pk>[0-9]+)/new',
        DeclarationCreationView.as_view(),
        name='insert_declaration'),
   url(r'^(?P<slug>[\w-]+)/declarations/(?P<pk>[0-9]+)',
        DeclarationEditView.as_view(),
        name='edit_declaration'),
   url(r'^(?P<slug>[\w-]+)/declarations/new',
        DeclarationCreationView.as_view(),
        name='new_declaration'),
    url(r'^(?P<slug>[\w-]+)/publish',
        ResolutionPublishView.as_view(),
        name='resolution_publish'),
    url(r'^(?P<slug>[\w-]+)/unpublish',
        ResolutionUnpublishView.as_view(),
        name='resolution_unpublish'),
    url(r'^(?P<slug>[\w-]+)/delete',
        ResolutionDeleteView.as_view(),
        name='resolution_delete'),
]
