# Generated by Django 5.2.12 on 2026-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_position', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain'), ('absent', 'Absent')], max_length=10)),
            ],
            options={
                'db_table': 'country_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_symbol', models.CharField(max_length=50)),
                ('adopted_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.CharField(max_length=2)),
                ('session', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'resolutions',
                'ordering': ['draft_symbol'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('consensus', 'Consensus'), ('recorded', 'Recorded Vote')], max_length=20)),
                ('vote_scope', models.CharField(choices=[('whole_resolution', 'Whole Resolution'), ('paragraph', 'Paragraph'), ('amendment', 'Amendment')], max_length=20)),
                ('paragraph_number', models.IntegerField(blank=True, null=True)),
                ('yes_count', models.IntegerField(blank=True, null=True)),
                ('no_count', models.IntegerField(blank=True, null=True)),
                ('abstain_count', models.IntegerField(blank=True, null=True)),
                ('position_in_item', models.IntegerField()),
            ],
            options={
                'db_table': 'votes',
                'managed': False,
            },
        ),
    ]
