# Generated by Django 5.2.12 on 2026-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('un_member_since', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
