# Generated by Django 5.2.12 on 2026-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('body', models.CharField(choices=[('GA', 'General Assembly'), ('SC', 'Security Council')], max_length=2)),
                ('meeting_number', models.IntegerField()),
                ('session', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-date', '-meeting_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('item_type', models.CharField(choices=[('agenda_item', 'Agenda Item'), ('other_item', 'Other Item')], max_length=20)),
                ('title', models.TextField()),
                ('agenda_number', models.IntegerField(blank=True, null=True)),
                ('sub_item', models.CharField(blank=True, max_length=10, null=True)),
                ('continued', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'document_items',
                'ordering': ['position'],
                'managed': False,
            },
        ),
    ]
