# Generated by Django 5.2.12 on 2026-03-13 20:30

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0002_create_unified_search_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=20)),
                ('item_id', models.IntegerField()),
                ('document_id', models.IntegerField(null=True)),
                ('document_symbol', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('body', models.CharField(max_length=2, null=True)),
                ('session', models.IntegerField(null=True)),
                ('speaker_id', models.IntegerField(null=True)),
                ('speaker_name', models.CharField(max_length=300, null=True)),
                ('country_id', models.IntegerField(null=True)),
                ('country_name', models.CharField(max_length=300, null=True)),
                ('country_iso3', models.CharField(max_length=3, null=True)),
                ('content', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                'db_table': 'search_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechSearchIndex',
            fields=[
                ('speech_id', models.IntegerField(primary_key=True, serialize=False)),
                ('document_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=30)),
                ('date', models.DateField(null=True)),
                ('body', models.CharField(max_length=2)),
                ('session', models.IntegerField()),
                ('speaker_id', models.IntegerField()),
                ('speaker_name', models.CharField(max_length=300)),
                ('country_id', models.IntegerField(null=True)),
                ('country_name', models.CharField(max_length=300, null=True)),
                ('text', models.TextField()),
                ('search_vector', models.TextField()),
            ],
            options={
                'db_table': 'speech_search_index',
                'managed': False,
            },
        ),
    ]
